const SET_USER='SET_USER';
const SET_ERROR='SET_ERROR';
const SET_BOOK='SET_BOOK';
const INVALIDATE='INVALIDATE';
const SET_SEARCHED='SET_SEARCHED';
const UPDATE_BOOK='UPDATE_BOOK';
const UPDATE_SEARCHED_BOOK= 'UPDATE_SEARCHED_BOOK'

export { SET_USER, SET_ERROR, SET_BOOK,SET_SEARCHED, UPDATE_BOOK, UPDATE_SEARCHED_BOOK, INVALIDATE};